version: '3'
services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - 80:80
    links:
      - mariadb
    volumes:
      - drupal_data:/bitnami/drupal

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_USER=LinuxSistem
      - MARIADB_PASSWORD=030121049
      - MARIADB_DATABASE=mart
    volumes:
      - mariadb_data:/bitnami/mariadb

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  certbot:
    image: certbot/certbot
    volumes:
      - letsencrypt:/etc/letsencrypt

volumes:
  drupal_data:
    driver: local
  mariadb_data:
    driver: local
  letsencrypt:
    driver: local
